name: doc

on:
  push:
    branches: ["main"]
    tags: ["*"]

# Prevent doc action on `main` to conflict with each others.
concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: env.yml
          environment-name: datamol
          cache-downloads: true
          cache-env: true

      - name: Install library
        run: python -m pip install --no-deps .

      - name: Deploy the doc
        run: |
          echo "Configure git"
          git config --global user.name 'hadim'
          git config --global user.email 'hadim@users.noreply.github.com'

          echo "Get the gh-pages branch"
          git fetch origin gh-pages

          TAG_OR_BRANCH_NAME=${GITHUB_REF##*/}

          if [ $TAG_OR_BRANCH_NAME = "main" ]; then
            echo "Build and deploy the doc on main"
            mike deploy --push --force main
          else
            echo "Build and deploy the doc on $TAG_OR_BRANCH_NAME"

            mike deploy --push --force stable
            mike deploy --push --force $TAG_OR_BRANCH_NAME
          fi
