name: doc

on:
  push:
    branches: ["master"]
    tags: ["*"]

jobs:
  doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 3
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('env.yml') }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          use-only-tar-bz2: true
          auto-activate-base: true
          activate-environment: ""

      - name: Install Dependencies
        run: |
          mamba create -n datamol
          conda activate datamol
          mamba env update -f env.yml

      - name: Install library
        run: |
          conda activate datamol
          python -m pip install .

      - name: Deploy the doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda activate datamol

          echo "Configure git"
          git config --global user.name 'hadim'
          git config --global user.email 'hadim@users.noreply.github.com'

          echo "Get the gh-pages branch"
          git fetch origin gh-pages

          echo "Regenerate the API doc"
          python -m datamol._mkdocs

          echo "Build and deploy the doc"
          if [ $GITHUB_REF = "master" ]; then
            mike deploy --push master
          else
            mike deploy --push stable
            mike deploy --push $GITHUB_REF
          fi

          echo "Define the default version to serve"
          mike set-default --push stable
